network_id: overengineers-anonymous
node_config:
  - node_id: chkpwd
  - node_id: thomson
  - node_id: jens-beryjuio-home
  - node_id: ripple-01
    url: grpcs://mesh-01.ripplefcl.com:443
  - node_id: ripple-02
    url: grpcs://mesh-02.ripplefcl.com:443
  - node_id: vt153-home
    url: grpc://mm.mayonline.co.uk:42069
  - node_id: jens-beryjuio-prod
    url: grpcs://meshmon-grpc.beryjuio-prod.k8s.beryju.io
  - node_id: jens-beryjuio-oci
    url: grpcs://meshmon-grpc.beryjuio-oci.k8s.beryju.io
  - node_id: will-lab-ovh
    url: grpc://51.195.226.54:42069
  - node_id: will-lab-home
    url: grpcs://meshmon.mcda.dev:443

rebroadcasts:
  - src_net: home-local
    apply_to:
      - ripple-01
      - ripple-02
    group_prefix: ripple-
  - src_net: local
    apply_to: []
      # - will-lab-home
    group_prefix: mcda-

cluster:
  rate_limits:
    update: 10
    priority_update: 2
  clock_pulse_interval: 20
  avg_clock_pulses: 5

node_version:
  - ">=4.0.0-beta.7"
  - "<5.0.0"
