network_id: overengineers-anonymous
node_config:
  - node_id: chkpwd
  - node_id: ripple
    url: grpcs://mesh.ripplefcl.com:443
  - node_id: vt153-home
    url: grpc://mm.mayonline.co.uk:42069
  - node_id: thomson
  - node_id: jens-beryjuio-prod
    url: grpcs://meshmon-grpc.beryjuio-prod.k8s.beryju.io
  - node_id: jens-beryjuio-home
  - node_id: jens-beryjuio-oci
    url: grpcs://meshmon-grpc.beryjuio-oci.k8s.beryju.io
  - node_id: will-lab-ovh
    url: grpc://51.195.226.54:42069
  - node_id: will-lab-home
    url: grpcs://meshmon.mcda.dev:443
    network_id: overengineers-anonymous
node_config:
  - node_id: chkpwd
  - node_id: ripple
    url: grpcs://mesh.ripplefcl.com:443

  - node_id: thomson
  - node_id: jens-beryjuio-prod
    url: grpcs://meshmon-grpc.beryjuio-prod.k8s.beryju.io
  - node_id: jens-beryjuio-home
  - node_id: jens-beryjuio-oci
    url: grpcs://meshmon-grpc.beryjuio-oci.k8s.beryju.io
  - node_id: will-lab-ovh
    url: grpc://51.195.226.54:42069
  - node_id: will-lab-home
    url: grpcs://meshmon.mcda.dev:443
  - node_id: vt153-home
    url: grpcs://mm.mayonline.co.uk:42069

rebroadcasts:
  - src_net: home-local
    apply_to:
      - ripple
    group_prefix: ripple-
  - src_net: local
    apply_to:
      - will-lab-home
    group_prefix: mcda-
node_version:
  - ">=4.0.0-beta.7"
  - "<5.0.0"

rebroadcasts:
  - src_net: home-local
    apply_to:
      - ripple
    group_prefix: ripple-
  - src_net: local
    apply_to:
      - will-lab-home
    group_prefix: mcda-
node_version:
  - ">=4.0.0-beta.7"
  - "<5.0.0"
