network_id: overengineers-anonymous
node_config:
  # - node_id: chkpwd
  #   url: https://meshmon.chkpwd.com
  - node_id: ripple
    url: grpcs://mesh.ripplefcl.com:443
    rebroadcast:
      - src_net: home-local
        prefix: "rhl-"
  - node_id: thomson
  - node_id: jens-beryjuio-prod
    url: grpcs://meshmon-grpc.beryjuio-prod.k8s.beryju.io
  - node_id: jens-beryjuio-home
  - node_id: jens-beryjuio-oci
    url: grpcs://meshmon-grpc.beryjuio-oci.k8s.beryju.io
#   - node_id: will-lab-ovh
#     url: http://51.195.226.54:8000
  - node_id: will-lab-home
    url: grpcs://meshmon.mcda.dev:443

node_version:
  - ">=3.0.0"
  - "<5.0.0"
